[package]
name = "runifold-core"
description = "Runtime kernel primitives for Runifold"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
event-listener.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
futures-executor.workspace = true

[lints]
workspace = true

[target.wasm32-unknown-unknown.dev-dependencies]
wasm-bindgen-test = "0.3.76"

[target.wasm32-unknown-unknown.dependencies]
web-time = "1"
